site_name: splitfxm
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Getting Started: start.md
  - Benchmark: benchmark.md
  - Pricing: pricing.md
  - Code Documentation:
      - Overview: api.md
      - Model: model.md
      - Domain: domain.md
      - Initial Conditions: ic.md
      - Boundary Conditions: bc.md
      - Finite-Volume Schemes: flux.md
      - Finite-Difference Schemes:
        - Overview: derivatives.md
        - Scheme Generation: generate.md
      - Visualization: visualize.md
      - Tutorials:
        - Advection-Diffusion: tutorials/advection_diffusion.md
        - Sod Shock Tube: tutorials/sod_shock.md
        - Conservative Sod Shock Tube: tutorials/conservative_sod_shock.md
      - Adaptive Mesh Refinement: refine.md
      - Internals:
        - Overview: internals.md
        - Cell: cell.md
        - Boundary: boundary.md
        - System: system.md
        - Simulation: simulation.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            members_order: source

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math

extra_css:
  - assets/docs.css